= 2ntrip API Docs
Powered By Dongwhwan Lee, https://github.com/hwanld
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 1
:sectlinks:

[[Users_save]]
== Users_save

operation::Users_save[snippets='http-request,request-body,request-fields,http-response,response-body,response-fields']

[[Users_isExistNickname]]
== Users_isExistNickname

operation::Users_isExistNickname[snippets='http-request,path-parameters,http-response,response-body,response-fields']

[[Users_isExistUserId]]
== Users_isExistUserId

operation::Users_isExistUserId[snippets='http-request,path-parameters,http-response,response-body,response-fields']

[[Users_isExistNickname_failCase]]
== Users_isExistNickname_failCase

operation::Users_isExistNickname_failCase[snippets='http-request,path-parameters,http-response,response-body,response-fields']

[[Users_isExistUserId_failCase]]
== Users_isExistUserId_failCase

operation::Users_isExistUserId_failCase[snippets='http-request,path-parameters,http-response,response-body,response-fields']

[[Users_login]]
== Users_login

operation::Users_login[snippets='http-request,request-body,request-fields,http-response,response-body,response-fields']

[[Users_login_failById]]
== Users_login_failById

operation::Users_login_failById[snippets='http-request,request-body,request-fields,http-response,response-body,response-fields']

[[Users_login_failByPassword]]
== Users_login_failByPassword

operation::Users_login_failByPassword[snippets='http-request,request-body,request-fields,http-response,response-body,response-fields']

[[Users_addToken]]
== Users_addToken

operation::Users_addToken[snippets='http-request,request-headers,path-parameters,http-response,response-body,response-fields']

[[Users_findById]]
== Users_findById

operation::Users_findById[snippets='http-request,request-headers,path-parameters,http-response,response-body,response-fields']

[[Users_findById_failCase]]
== Users_findById_failCase

operation::Users_findById_failCase[snippets='http-request,request-headers,path-parameters,http-response,response-body,response-fields']

[[Users_findUsersWithNicknameOrUserId]]
== Users_findUsersWithNicknameOrUserId

operation::Users_findUsersWithNicknameOrUserId[snippets='http-request,request-headers,path-parameters,http-response,response-body,response-fields']

[[Users_findUsersWithNicknameOrUserId_failCase]]
== Users_findUsersWithNicknameOrUserId_failCase

operation::Users_findUsersWithNicknameOrUserId_failCase[snippets='http-request,request-headers,path-parameters,http-response,response-body,response-fields']

[[Users_addPlanners]]
== Users_addPlanners

operation::Users_addPlanners[snippets='http-request,request-headers,path-parameters,http-response,response-body,response-fields']

[[Users_findAllPlannersWithUserId]]
== Users_findAllPlannersWithUserId

operation::Users_findAllPlannersWithUserId[snippets='http-request,request-headers,path-parameters,http-response,response-body,response-fields']

[[Users_Logout]]
== Users_Logout

operation::Users_Logout[snippets='http-request,request-headers,path-parameters,http-response,response-body,response-fields']