drop table if exists comments CASCADE

drop table if exists notices CASCADE

drop table if exists photos CASCADE

drop table if exists planners CASCADE

drop table if exists planners_users CASCADE

drop table if exists plans CASCADE

drop table if exists posts CASCADE

drop table if exists posts_like_users CASCADE

drop table if exists posts_comments CASCADE

drop table if exists posts_nested_comments CASCADE

drop table if exists users CASCADE

drop table if exists users_like_posts CASCADE

drop table if exists users_planners CASCADE

drop table if exists users_votes_contents CASCADE

drop table if exists votes CASCADE

drop table if exists votes_contents CASCADE

drop table if exists votes_contents_users_set CASCADE

drop sequence if exists hibernate_sequence

create sequence hibernate_sequence start with 1 increment by 1

create table comments
(
    comment_id bigint generated by default as identity,
    author     varchar(255),
    content    varchar(255),
    plan_id    bigint,
    user_id    varchar(255),
    primary key (comment_id)
)

create table notices
(
    notice_id    bigint generated by default as identity,
    created_date timestamp,
    timestamp    timestamp,
    content      varchar(255),
    title        varchar(255),
    user_id      varchar(255),
    planner_id   bigint,
    primary key (notice_id)
)

create table photos
(
    photo_id     bigint generated by default as identity,
    created_date timestamp,
    timestamp    timestamp,
    file_name    varchar(255),
    photo_url    varchar(255),
    priority     bigint,
    post_id      bigint,
    primary key (photo_id)
)

create table planners
(
    planner_id         bigint generated by default as identity,
    created_date       timestamp,
    timestamp          timestamp,
    comment_time_stamp timestamp,
    end_date           varchar(255),
    start_date         varchar(255),
    title              varchar(255),
    primary key (planner_id)
)

create table planners_users
(
    planners_planner_id bigint       not null,
    users_user_id       varchar(255) not null,
    primary key (planners_planner_id, users_user_id)
)

create table plans
(
    plan_id    bigint generated by default as identity,
    date       varchar(255),
    location   varchar(255),
    rgb        bigint not null,
    time       varchar(255),
    todo       varchar(255),
    planner_id bigint,
    primary key (plan_id)
)

create table posts
(
    post_id         bigint generated by default as identity,
    created_date    timestamp,
    timestamp       timestamp,
    comments_number bigint not null,
    content         varchar(255),
    like_number     bigint not null,
    post_tag        varchar(255),
    title           varchar(255),
    user_id         varchar(255),
    primary key (post_id)
)

create table posts_like_users
(
    posts_post_id      bigint       not null,
    like_users_user_id varchar(255) not null,
    primary key (posts_post_id, like_users_user_id)
)

create table posts_comments
(
    post_comment_id bigint generated by default as identity,
    created_date    timestamp,
    timestamp       timestamp,
    content         varchar(255),
    user_id         varchar(255),
    post_id         bigint,
    primary key (post_comment_id)
)

create table posts_nested_comments
(
    post_nested_comment_id bigint generated by default as identity,
    created_date           timestamp,
    timestamp              timestamp,
    content                varchar(255),
    user_id                varchar(255),
    post_comment_id        bigint,
    primary key (post_nested_comment_id)
)

create table users
(
    user_id      varchar(255) not null,
    created_date timestamp,
    timestamp    timestamp,
    gender       integer,
    m_password   varchar(255),
    nickname     varchar(255),
    photo_url    varchar(255),
    token        varchar(255),
    primary key (user_id)
)

create table users_like_posts
(
    users_user_id      varchar(255) not null,
    like_posts_post_id bigint       not null,
    primary key (users_user_id, like_posts_post_id)
)

create table users_planners
(
    users_user_id       varchar(255) not null,
    planners_planner_id bigint       not null,
    primary key (users_user_id, planners_planner_id)
)

create table users_votes_contents
(
    users_user_id                   varchar(255) not null,
    votes_contents_votes_content_id bigint       not null,
    primary key (users_user_id, votes_contents_votes_content_id)
)

create table votes
(
    vote_id        bigint  not null,
    anonymous_vote boolean not null,
    dead_line      timestamp,
    multiple_vote  boolean not null,
    title          varchar(255),
    voting         boolean not null,
    user_id        varchar(255),
    planner_id     bigint,
    primary key (vote_id)
)

create table votes_contents
(
    votes_content_id bigint generated by default as identity,
    created_date     timestamp,
    timestamp        timestamp,
    contents         varchar(255),
    selected_count   integer not null,
    vote_id          bigint,
    votes            bigint,
    primary key (votes_content_id)
)

create table votes_contents_users_set
(
    votes_contents_votes_content_id bigint       not null,
    users_set_user_id               varchar(255) not null,
    primary key (votes_contents_votes_content_id, users_set_user_id)
)

alter table posts_like_users
    add constraint UK_mbum5xr4a8q5uha05rd7d1dvv unique (like_users_user_id)

alter table users_like_posts
    add constraint UK_1mq44ofg4yfrf7enyk0wyo891 unique (like_posts_post_id)

alter table comments
    add constraint FKf0340npvkkasvyk0q2nppxxcq foreign key (plan_id) references plans

alter table comments
    add constraint FK8omq0tc18jd43bu5tjh6jvraq foreign key (user_id) references users

alter table notices
    add constraint FKerqkxcii6jcl64muyrcxm10sp foreign key (user_id) references users

alter table notices
    add constraint FKcl7fc7vn1y8yb86gkt0wgnsyg foreign key (planner_id) references planners

alter table photos
    add constraint FK6y417rkxpq0v9rurdmrj96034 foreign key (post_id) references posts

alter table planners_users
    add constraint FKs0eobv8w64e4wump7igd9ig2c foreign key (users_user_id) references users

alter table planners_users
    add constraint FKk39bxuxi0u9j29rjl3afnbwyh foreign key (planners_planner_id) references planners

alter table plans
    add constraint FK1e77270nvocc17cl9sd8hbpqq foreign key (planner_id) references planners

alter table posts
    add constraint FK5lidm6cqbc7u4xhqpxm898qme foreign key (user_id) references users

alter table posts_like_users
    add constraint FK7gsopd6wija40sp43rs2uxd foreign key (like_users_user_id) references users

alter table posts_like_users
    add constraint FKg35gg90k1y1tc2buae3ra3ne foreign key (posts_post_id) references posts

alter table posts_comments
    add constraint FKv7itstygb5hqafy1qs84kyiw foreign key (user_id) references users

alter table posts_comments
    add constraint FKbjdq8a62c5siv1mk27umswg9 foreign key (post_id) references posts

alter table posts_nested_comments
    add constraint FKlk3mnib9en043jcqtfln1pf3o foreign key (user_id) references users

alter table posts_nested_comments
    add constraint FKgsmky4hd0fbmyyskyxk9qbgib foreign key (post_comment_id) references posts_comments

alter table users_like_posts
    add constraint FK787tchxc6jvnir9j2olf7o4wv foreign key (like_posts_post_id) references posts

alter table users_like_posts
    add constraint FKovtfhplay63a101ts7xjg6dgq foreign key (users_user_id) references users

alter table users_planners
    add constraint FK2dsm2tn7t5bnualk5b3oipoom foreign key (planners_planner_id) references planners

alter table users_planners
    add constraint FKqo3togsg04kgb6wd98ms05vjw foreign key (users_user_id) references users

alter table users_votes_contents
    add constraint FKj8yxdux7vpnxt7vmedyd6dta0 foreign key (votes_contents_votes_content_id) references votes_contents

alter table users_votes_contents
    add constraint FKdn28wtfkkwqyew55vpjjyraoa foreign key (users_user_id) references users

alter table votes
    add constraint FKli4uj3ic2vypf5pialchj925e foreign key (user_id) references users

alter table votes
    add constraint FKiirluxgurps4fmiyjyashcdvl foreign key (planner_id) references planners

alter table votes_contents
    add constraint FKhgvbsohec12icsx0dlnuani31 foreign key (vote_id) references votes

alter table votes_contents
    add constraint FKkn96u7owanejpkm6358munio6 foreign key (votes) references votes

alter table votes_contents_users_set
    add constraint FK5ahq5lpylujnby4ydwou9meub foreign key (users_set_user_id) references users

alter table votes_contents_users_set
    add constraint FKcf0chjv46oca7ahntvhdrglxs foreign key (votes_contents_votes_content_id) references votes_contents
